server:
  port: 80
spring:
  application:
    name: CLOUD-ORDER-SERVICE

eureka:
  instance:
    instance-id: orderfeign80
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    #register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    #fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  #建立连接后
  ConnectTimeout: 500
  #建立连接所需要的时间
  ReadTimeout: 5000


logging:
  level:
    #fegin监控的哪个端口，什么级别
    com.lk.sc.fegin.PaymentFeignService: debug